### ISSUE TITLE
An error and a deprecation warning while loading "PBMBinary" format

### ISSUE THREAD

**Issue by magister-ludi** [JuliaIO/Netpbm.jl#22]
In the function
```load(s::Stream{format"PBMBinary"})```
the constructor `BitArray(w, h)` is called. This should now be `BitArray(undef, w, h)`. In the function
```load(s::Stream{format"PBMBinary"})```
the call to `permuteddimsview` has been deprecated. This should now be `PermutedDimsArray` (since [ImageCore version 0.8.17](https://github.com/JuliaImages/ImageCore.jl/releases/tag/v0.8.17)).

I discovered this while adding methods for reading and writing "plain" `Netpbm` formats. I have code that fixes this issue (including added tests for `"PBMBinary"` format), and code that adds I/O for plain formats. I can submit this as a single PR, or two separate PRs, whichever seems best.

**Comment by timholy** [comment]
I'd gladly take either option, whichever you prefer. Thanks in advance!
