### ISSUE TITLE
TagBot did not run for 1.0

### ISSUE THREAD

**Issue by timholy** [JuliaIO/Netpbm.jl#25]
The "releases" tab does not list 1.0 despite it having been merged 8 days ago: https://github.com/JuliaRegistries/General/pull/23666

**Comment by johnnychen94** [comment]
Probably it's because Project.toml uses `1.0` instead of `1.0.0`. I just modified it back to the standard syntax in a1f8b38
 but the `v1.0.0` tag seems to be made quite long ago that TagBot doesn't discover.

I manually made a release for this.

cc: @magister-ludi

**Comment by magister-ludi** [comment]
My apologies, this was the first time I had done this. Once the correct version appeared on [JuliaHub](https://juliahub.com/ui/Packages/Netpbm/66P7n/1.0.0) I just assumed it had worked. Thanks for fixing it.
