### ISSUE TITLE
Differentiate netpbm sub-formats by magic number

### ISSUE THREAD

**Issue by tecosaur** [JuliaIO/Netpbm.jl#39]
Currently, this package handles the variation in Netpbm files by requiring that an `IOStream` be wrapped in a certain `FileIO.Format`.

However, the various Netpbm sub-formats (pbm, pgm, and ppm) can also be identified by their magic number. If Netpbm could use this to provide a generic `Netpbm.load(::IO)` method, I think that would be quite convenient.

**Comment by magister-ludi** [comment]
This is already handled by `FileIO.jl`. That package has
```julia
load(strm)
```
which uses the magic number to decide which `Format` subtype to use for wrapping `strm`, where `strm` is "an `IOStream` or similar object". If you have
```julia
using FileIO
using ImageIO
```
then `FileIO.load` has the convenience you're looking for.
